---
language: python
python: "2.7"
sudo: required

env:
  - VERSION=1.1.19 HASH=5790cb
  - VERSION=1.1.15 HASH=022a51

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # Install ansible
  - if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install ansible; else pip install ansible==$ANSIBLE_VERSION; fi

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  # Basic role syntax check
  - >
    ansible-playbook tests/test.yml -i tests/inventory --connection=local --syntax-check
    --extra-vars "version=$VERSION hash=$HASH"

  # Run the role
  - >
    ansible-playbook -i tests/inventory tests/test.yml --connection=local
    --extra-vars "version=$VERSION hash=$HASH"

  # Idempotent test
  - >
    ansible-playbook -i tests/inventory tests/test.yml --connection=local
    --extra-vars "version=$VERSION hash=$HASH"
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
...
