---
- name: install yii
  unarchive:
    src: "{{ yii_download_url }}/{{ yii_version }}/yii-{{ yii_version }}.{{ yii_hash }}.tar.gz"
    dest: "{{ yii_dest }}/"
    copy: no

- name: remove lines from test
  replace:
    dest: "{{ yii_dest }}/yii-{{ yii_version }}.{{ yii_hash }}/framework/test/CTestCase.php"
    regexp: ^(require_once.*)
    replace: //\1
...