---
- name: install yii
  unarchive:
    src: "{{ yii_download_url }}/{{ yii_version }}/yii-basic-app-{{ yii_version }}.tgz"
    dest: "{{ yii_dest }}/"
    copy: no

- name: stat yii
  stat: path="{{ yii_dest }}/basic"
  register: yii_stat

- name: move yii
  command: mv "{{ yii_dest }}/basic" "{{ yii_dest }}/yii-{{ yii_version }}.{{ yii_hash }}"
...
